language: node_js
notifications:
  slack: kiirus:kYXYWFfVV7FGS9R0rMj1l11a
node_js:
 - "6.7.0"
before_install:
 - "wget https://cdn.kiir.us/ci/.env"
 - "npm install nodeunit -g"
before_script:
 - "./node_modules/jshint/bin/jshint server.js"
